config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks"}
  resources :project_lists do
  	resources :project_tasks do
  		member do
  			patch :complete
  		end
      member do
        patch :edit
      end
      member do
        patch :new
      end
  		member do
  			patch :deadline
  		end
  	end
  end
  
  root "project_lists#index"

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project_list.rb
class ProjectList < ApplicationRecord
	belongs_to :user
	has_many :project_tasks, dependent: :destroy
end

app/models/project_task.rb
class ProjectTask < ApplicationRecord
  mount_uploader :image, FileUploader
  belongs_to :project_list 

  

  def completed?
  	!completed_at.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :project_lists

  

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: false) do |user|
       user.attributes = params
       user.valid? 
      end

    else
      super
    end

  end

  def password_required?
    super && provider.blank?
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def facebook
		user = User.from_omniauth(request.env["omniauth.auth"])
		if user.persisted?
			sign_in_and_redirect user, notice: "Signed in!"
		else
			session["devise.user_attributes"]  = user.user_attributes
			redirect_to new_user_registration_path
		end
	end
end

app/controllers/project_lists_controller.rb
class ProjectListsController < ApplicationController
  
  before_action :set_project_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /project_lists
  # GET /project_lists.json
  def index
    @project_lists = ProjectList.all
  end

  # GET /project_lists/1
  # GET /project_lists/1.json
  def show
  end

  # GET /project_lists/new
  def new
    @project_list = current_user.project_lists.build
    # ProjectList.new
  end

  # GET /project_lists/1/edit
  def edit
  end

  # POST /project_lists
  # POST /project_lists.json
  def create
    @project_list = current_user.project_lists.build(project_list_params)

    respond_to do |format|
      if @project_list.save
        format.html { redirect_to @project_list, notice: 'Project list was successfully created.' }
        format.json { render :show, status: :created, location: @project_list }
      else
        format.html { render :new }
        format.json { render json: @project_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_lists/1
  # PATCH/PUT /project_lists/1.json
  def update
    respond_to do |format|
      if @project_list.update(project_list_params)
        format.html { redirect_to @project_list, notice: 'Project list was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_list }
      else
        format.html { render :edit }
        format.json { render json: @project_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_lists/1
  # DELETE /project_lists/1.json
  def destroy
    @project_list.destroy
    respond_to do |format|
      format.html { redirect_to project_lists_url, notice: 'Project list was successfully destroyed.' }
      format.json { head :no_content }
      
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_list
      @project_list = ProjectList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_list_params
      params.require(:project_list).permit(:title, :description)
    end
end

app/controllers/project_tasks_controller.rb
class ProjectTasksController < ApplicationController

before_action :set_project_list
before_action :set_project_task, except: [:create, :new]


	def create
		@project_task = @project_list.project_tasks.create(project_task_params)
		redirect_to @project_list
	end
	
  	def new
    	@project_task = @project_list.project_tasks.build
    end
  
  def destroy
		if @project_task.destroy
			flash[:success] = "Task was deleted."
		else
			flash[:error] = "Task could not be deleted."
		end
		redirect_to @project_list
	end

	def complete
		@project_task.update_attribute(:completed_at, Time.now)
		redirect_to @project_list, notice: "Task Done"
	end

	

 private

  def set_project_list
   @project_list = ProjectList.find(params[:project_list_id])
  end

  def set_project_task
  	@project_task = @project_list.project_tasks.find(params[:id])
  end

  def project_task_params
   	
   	params[:project_task].permit(:content, :image, :task_deadline)
  end

 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/project_lists_helper.rb
module ProjectListsHelper
end

app/helpers/project_tasks_helper.rb
module ProjectTasksHelper
end

app/views/layouts/_navigation.html.erb
 <% if current_user %>
	<li> Hello, <%= current_user.email %></li>
	<li><%= link_to "Sign Out",  destroy_user_session_path, method: :delete %></li>
	

	<% else %>
	<h2 style = "color:white">Welcome!!</h2>
	<div>
		<%= link_to "Sign Up", new_user_registration_path %>
		<i class ="fa fa-sign-in"></i>
	</div>
	<div>
	<%= link_to "Sign In", new_user_session_path %>
	</div>
	<div>
	<%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'=> true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
     
  	<div class="container">
     <!--<p class="notice"><%= notice %></p>-->
     <p class="alert"><%= alert %></p>
     
     <%= render 'layouts/navigation' %>
  		<%= yield %>
  	</div>


    
  </body>
</html>

app/views/project_lists/_form.html.erb
<%= form_with(model: project_list, local: true) do |form| %>
  <% if project_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project_list.errors.count, "error") %> prohibited this project_list from being saved:</h2>

      <ul>
      <% project_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :project_list_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :project_list_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/project_lists/edit.html.erb
<h1 class="project_list_title">Editing Project</h1>

<div class="forms">
<%= render 'form', project_list: @project_list %>
</div>

<div class="links">
<%= link_to 'Cancel', project_lists_path %>
</div>

app/views/project_lists/index.html.erb
<div class="forms">

<!--<%= @project_lists.each do |project_list| %>-->

	  <div class="index_row_clearfix">

	  	<% if project_list.user == current_user %>
	  		  	
		    <h3 class="project_list_title"><%= link_to project_list.title, project_list %></h3>
		    <p class="project_list_sub_title"><%= project_list.description %></p>
	    

	     <% end %>   
	  </div> 	
<!--<% end %>-->
		<% if current_user %>
		<div class="links">
		<%= link_to "New Project", new_project_list_path %>
		</div>
		<% end %>
		

</div>

app/views/project_lists/new.html.erb
<h1 class="project_list_title">New Project</h1>

<div class="forms">
	<%= render 'form', project_list: @project_list %>
</div>

<div class="links">
	<%= link_to 'Back', project_lists_path %>
</div>

app/views/project_lists/show.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h2 class="project_list_title"><%= @project_list.title %></h2>
<p class="project_list_sub_title"><%= @project_list.description %></p>

<div id="project_tasks_wrapper">
    
    <%= render @project_list.project_tasks %>

	<div id="form">
		<%= render "project_tasks/form" %>
	</div>
	
</div>

<div class="links">
  <%= link_to 'Update Project', edit_project_list_path(@project_list) %> |
  <%= link_to 'Delete Project', @project_list, method: :delete, data: {confirm: "Do you want to delete the project?"} %> |
  <%= link_to 'Back', project_lists_path %>
</div>

app/views/project_tasks/_form.html.erb
<%= form_for([@project_list, @project_list.project_tasks.build]) do |f| %>

<% end %>
<div class="links">
		<%= link_to "Add Task", new_project_list_project_task_path(@project_list) %>
</div>

app/views/project_tasks/_project_task.html.erb
<div class="row clearfix">
	<% if project_task.completed? %>
	   <div class="complete">
	   	<%= link_to complete_project_list_project_task_path(@project_list, project_task.id), method: :patch do %>
	   	<i style="opacity: 0.4;" class ="fa fa-check"></i>
	   	<% end %>
	   </div>

	   <div class="project_task">
	   	<p style="opacity: 0.9;"><strike><%= project_task.content %></strike></p>
	   </div>

	   <div class="deadline">
	   	<p style="opacity: 0.9;"><strike><%= project_task.task_deadline %></strike></p>
	   </div>

	   <div class="field">
	   <p style="opacity: 0.9;"><strike><img src ="<%= project_task.image %>"></strike></p>
	   </div>

	   <div class="trash">
		   	<%= link_to project_list_project_task_path(@project_list, project_task.id), method: :delete, data: {confirm: "Do you want to delete the task?"} do %>
		   	<i class ="fa fa-trash"></i>
		   	<% end %>
		</div>
	   
	   
	<% else %>
		<div class="complete">
	   	<%= link_to complete_project_list_project_task_path(@project_list, project_task.id), method: :patch do %>
	   	<i class ="fa fa-check"></i>
	   	<% end %>
	   </div>

	   <div class="project_task">
	   	<p><%= project_task.content %></p>
	   </div>

	   

	   <div class="deadline">
	   	<%= project_task.task_deadline %>
	   </div>

	   <div class="field">
	   <img src ="<%= project_task.image %>">
	   </div>

	   <div class="trash">
		   	<%= link_to project_list_project_task_path(@project_list, project_task.id), method: :delete, data: {confirm: "Do you want to delete the task?"} do %>
		   	<i class ="fa fa-trash"></i>
		   	<% end %>
		</div>
	   
	<% end %>

</div>

app/views/project_tasks/new.html.erb
<h1 class="project_list_title">Add New Task</h1>

<%= form_for([@project_list, @project_list.project_tasks.build]) do |f| %>

<div class="forms">
	<%= f.label :content %>
	<%= f.text_field :content, placeholder: "New Task" %>
</div>
&nbsp;&nbsp;
<div class="forms">
	<%= f.label :task_deadline %>
	<%= f.date_field :task_deadline%>
</div>
&nbsp;&nbsp;
<div class="forms">
	<%= f.label :choose_file %>
	<%= f.file_field :image, placeholder: "Choose file"%>
</div>
&nbsp;&nbsp;
<div class="actions">
    <%= f.submit %>
  </div>

<% end %>
<div class="links">
	<%= link_to 'Back', project_lists_path %>
</div>